// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./components/error/404.vue')['default']
    Card: typeof import('./components/card/Card.vue')['default']
    ChatBox: typeof import('./components/chatBox/chatBox.vue')['default']
    ChatQuestionBox: typeof import('./components/chatBox/chatQuestionBox/chatQuestionBox.vue')['default']
    ChatReplyBox: typeof import('./components/chatBox/chatReplyBox/chatReplyBox.vue')['default']
    CheckingInput: typeof import('./components/input/checkingInput/checkingInput.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    InfiniteScroll: typeof import('./components/infiniteScroll/InfiniteScroll.vue')['default']
    InformationCard: typeof import('./components/informationCard/informationCard.vue')['default']
    LoadersFour: typeof import('./components/loaders/loadersFour.vue')['default']
    LoadersFoure: typeof import('./components/loaders/loadersFoure.vue')['default']
    LoadersOne: typeof import('./components/loaders/loadersOne.vue')['default']
    LoadersThree: typeof import('./components/loaders/loadersThree.vue')['default']
    LoadersTwo: typeof import('./components/loaders/loadersTwo.vue')['default']
    LoadresThree: typeof import('./components/loaders/loadresThree.vue')['default']
    MoreSearchCard: typeof import('./components/moreSearchCard/moreSearchCard.vue')['default']
    NavbarHome: typeof import('./components/navbar/NavbarHome.vue')['default']
    PhoneOnInput: typeof import('./components/input/phoneOnInput/phoneOnInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultCard: typeof import('./components/searchResultCard/searchResultCard.vue')['default']
    Smiley: typeof import('./components/smiley/Smiley.vue')['default']
    ToolCard: typeof import('./components/toolCard/toolCard.vue')['default']
    UnderConstruction: typeof import('./components/error/underConstruction.vue')['default']
    VerifyInput: typeof import('./components/input/verifyInput/verifyInput.vue')['default']
  }
}
